### ISSUE TITLE
[compile error] Failed to compile BPF module <text>

### ISSUE THREAD

**Issue by AgnesWickfield** [MapleLCG/ebpf-tools-examples#1]
```bash
ubuntu@ubuntu:~$ sudo python3 DnsQuery-monitor.py 
/virtual/main.c:62:52: error: no member named 'iov' in 'struct iov_iter'
        const struct iovec * iov = msg -> msg_iter.iov;
                                   ~~~~~~~~~~~~~~~ ^
/virtual/main.c:105:52: error: no member named 'iov' in 'struct iov_iter'
        const struct iovec * iov = msg -> msg_iter.iov;
                                   ~~~~~~~~~~~~~~~ ^
... 2 errors generated.
Traceback (most recent call last):
  File "/home/ubuntu/DnsQuery-monitor.py", line 171, in <module>
    bpf_kprobe = BPF(text=C_BPF_KPROBE)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

Here is the context of the relevant error code:
```c
        struct msghdr * msg = (struct msghdr *)PT_REGS_PARM2(ctx);
        const struct iovec * iov = msg -> msg_iter.iov;
        // 获取iov结构体中的iov_base和iov_len字段
        void __user *iov_base = iov->iov_base;
        u32 iov_len = iov->iov_len;
        // 确保长度不超过domain的大小
        u32 len = iov_len < sizeof(key.domain) ? iov_len : sizeof(key.domain) - 1;

        //iov_base + 12，跳过DNS报文前12字节，直奔域名字段
        bpf_probe_read(&key.domain, len, iov_base+12);
```

**Env:** 
- VMware Linux ubuntu 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- sudo apt-get install bpfcc-tools linux-headers-$(uname -r)

**How can I solve it？**

**Comment by AgnesWickfield** [comment]
When I **_build and compile BCC from source_** to install the BCC tool, it works, instead of relying on Ubuntu binary packages from apt. I also change my VMware virtual machine to **Ubuntu 20.04** (Linux ubuntu **5.15.0-105-generic**).

**DnsQuery-monitor.py** works successfully in this case.

**Thanks for sharing the usages of eBPF tools very much!**

**Comment by MapleLCG** [comment]
> ```shell
> ```shell
> ubuntu@ubuntu:~$ sudo python3 DnsQuery-monitor.py 
> /virtual/main.c:62:52: error: no member named 'iov' in 'struct iov_iter'
>         const struct iovec * iov = msg -> msg_iter.iov;
>                                    ~~~~~~~~~~~~~~~ ^
> /virtual/main.c:105:52: error: no member named 'iov' in 'struct iov_iter'
>         const struct iovec * iov = msg -> msg_iter.iov;
>                                    ~~~~~~~~~~~~~~~ ^
> ... 2 errors generated.
> Traceback (most recent call last):
>   File "/home/ubuntu/DnsQuery-monitor.py", line 171, in <module>
>     bpf_kprobe = BPF(text=C_BPF_KPROBE)
>   File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 364, in __init__
>     raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
> Exception: Failed to compile BPF module <text>
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Here is the context of the relevant error code:
> ```c
>         struct msghdr * msg = (struct msghdr *)PT_REGS_PARM2(ctx);
>         const struct iovec * iov = msg -> msg_iter.iov;
>         // 获取iov结构体中的iov_base和iov_len字段
>         void __user *iov_base = iov->iov_base;
>         u32 iov_len = iov->iov_len;
>         // 确保长度不超过domain的大小
>         u32 len = iov_len < sizeof(key.domain) ? iov_len : sizeof(key.domain) - 1;
> 
>         //iov_base + 12，跳过DNS报文前12字节，直奔域名字段
>         bpf_probe_read(&key.domain, len, iov_base+12);
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Env:
> 
> VMware Linux ubuntu 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
> sudo apt-get install bpfcc-tools linux-headers-$(uname -r)
> 
> How can I solve it？
> ```

在内核版本6.5.0里，msg_iter里的iov成员改名字了，改成了__iov。这也是kprobe的坏处，版本的更迭可能会导致名字的变化，进而导致运行不起来。另外在ubuntu上不建议使用apt的安装办法，已经年久失修了。

**Comment by AgnesWickfield** [comment]
> 
> 在内核版本6.5.0里，msg_iter里的iov成员改名字了，改成了__iov。这也是kprobe的坏处，版本的更迭可能会导致名字的变化，进而导致运行不起来。另外在ubuntu上不建议使用apt的安装办法，已经年久失修了。

再次感谢作者的解答。msg_iter里的iov成员改成__iov后，在ubuntu22.04也可以成功运行`sudo python3 DnsQuery-monitor.py`了。然而意外的是，当我执行curl或ping命令时DOMAIN的值却无法正常打印。在ubuntu20.04使用时DOMAIN的值可以打印出来，一切正常。我不知道哪儿出了差错？

![image](https://github.com/MapleLCG/ebpf-tools-examples/assets/123758374/f2490292-6a9c-43ab-aaf8-9450dce81351)

![image](https://github.com/MapleLCG/ebpf-tools-examples/assets/123758374/3725bcbe-e6c1-42c6-a1a3-4a09def82363)

**Comment by MapleLCG** [comment]
> > 在内核版本6.5.0里，msg_iter里的iov成员改名字了，改成了__iov。这也是kprobe的坏处，版本的更迭可能会导致名字的变化，进而导致运行不起来。另外在ubuntu上不建议使用apt的安装办法，已经年久失修了。
> 
> 再次感谢作者的解答。msg_iter里的iov成员改成__iov后，在ubuntu22.04也可以成功运行`sudo python3 DnsQuery-monitor.py`了。然而意外的是，当我执行curl或ping命令时DOMAIN的值却无法正常打印。在ubuntu20.04使用时DOMAIN的值可以打印出来，一切正常。我不知道哪儿出了差错？
> 
> ![image](https://private-user-images.githubusercontent.com/123758374/329584904-f2490292-6a9c-43ab-aaf8-9450dce81351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTcwNjAsIm5iZiI6MTcxNTg1Njc2MCwicGF0aCI6Ii8xMjM3NTgzNzQvMzI5NTg0OTA0LWYyNDkwMjkyLTZhOWMtNDNhYi1hYWY4LTk0NTBkY2U4MTM1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxMDUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGZiNDMwYzViYmVjMmZlYTVmZWE3ZmI0Y2Y3ZmM1OTU0ZjMyYWM1OWI3OGZjYjU3OGE2YWI3OGVlZDJkMGI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5gGQRzC21XXoYtMX8aD_X568sdf-7IK-OjdRA2F8fT4)
> 
> ![image](https://private-user-images.githubusercontent.com/123758374/329586055-3725bcbe-e6c1-42c6-a1a3-4a09def82363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTcwNjAsIm5iZiI6MTcxNTg1Njc2MCwicGF0aCI6Ii8xMjM3NTgzNzQvMzI5NTg2MDU1LTM3MjViY2JlLWU2YzEtNDJjNi1hMWEzLTRhMDlkZWY4MjM2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxMDUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzRmYzVlZWE4ZTEyZjJmNmRkZjFlNzVlOTk2ZWJkN2E4NzVhNmFiMDlmZDg0ZDU4MjJlODgyZTU0YzAxNTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f_SAfnRWbr9Wa7jQVHlYRX0rV84cHhSQ9DOeiOE3SrA)

之前随便看了眼结构体的变化，以为改个名字就ok了，但并不是。实际上应该把代码改成这个
```
        const struct iovec iov = msg -> msg_iter.__ubuf_iovec;
        // 获取iov结构体中的iov_base和iov_len字段
        void __user *iov_base = iov.iov_base;
        u32 iov_len = iov.iov_len;
```
改成这样就没问题了

**Comment by AgnesWickfield** [comment]
感谢作者的答疑。ubuntu22.04（内核为Linux ubuntu **6.5.0-28-generic**）中将代码修改后，可以正确运行并打印进程的DNS查询了！
